-------------------DML(DATA MANIPULATION LANGUAGE)-----------------
--INSERT 
--UPDATE 
--DELLETE

--------------------INSERT--------------------------
--TO INSERT NEW ROW IN A TABLE
    --SYNTAX 1: INSERT INTO <TN> VALUES (VALUE1,VALUE2,......);
    --SYNTAX 2: INSERT INTO <TN> (<COLUMN NAMES>) VALUES (VALUE1,VALUE2,......)       

DESC KINGRK;    

INSERT INTO KINGRK VALUES (1,'KIRAN',5000000);

SELECT * FROM KINGRK;

INSERT INTO KINGRK (KID,KNAME,KSALARY) VALUES (2,'VENKU',60000000);

SELECT * FROM KINGRK;


-----SUBSTITUTIONAL OPERATOR
    --SYNTAX : INSERT INTO <TN> VALUES (&<COLUMN NAME1>,&<COLUMN NAME2>,........);

INSERT INTO KINGRK VALUES (&KID,'&KNAME',&KSALARY);

SELECT * FROM KINGRK;
 
 
-------------------------UPDATE----------------------------------

    --UPDATE ALL ROWS DATA IN A TABLEAT A TIME.
    --UPDATE SPECIFIC ROW DATA IN A TABLE BY USING "WHERE CLAUSE".
    --SYNTAX: UPDATE <TN> SET <COLUMN NAME1>= <VALUE1>, <COLUMN NAME2>= <VALUE2>,.......... [WHERE<CONDITION>];

SELECT * FROM EMP;

UPDATE EMP SET COMM= 100 WHERE EMPNO=7369; 

SELECT * FROM EMP;

------------------------DELETE-----------------------

    --DELETE ALL ROWSS FROM A TABLE AT A TIME
    --DELETE SPECIFIC ROW DATA IN A TABLE BY USING "WHERE CLAUSE".
    --SYNTAX: DELETE FROM <TN> [WHERE <CONDITION>];
    
SELECT * FROM EMP;

DESC EMP;

DELETE FROM EMP WHERE EMPNO=7788;

SELECT * FROM EMP;

ROLLBACK;       -- RESTORE DELETED ROW

SELECT * FROM EMP;

