-------------------SEQUENCE----------------------------------
    --IS A DB OBJECT WHICH IS USED TO GENERATE SEQUENCE NUMBERS IN A COLUMN.
    
    --SYNTAX:  CREATE SEQUENCE <SEQUENCE NAME> [START WITH N],[MIN VALUE N],[INCREMENT BY N],[MAX VAL N],[NO CYCLE],[NO CACHE N];
    
    --1) START WITH N
        --STARTING VALUE OF A SEQUENCE 'N'-NUMBERE.
    --2) MINVALUE N
        --SPECIFY MINIMUM VALUE IN SEQUENCE 'N'
    --3) INCREMENT BY N
        -- SPECIFY INCREMENTAL VALUE IN BEETWEEN SEQUENCE NUMBERS 'N'
    --4) MAX VALUE N
        --MAX VALUE IN SEQUENCE 'N'.
    --5) NO CYCLE
        --DEFAULT PARAMETER WHEN WE CREATE A SEQUENCE WITH 'NO CYCLE' PARAMETER THEN TE SET OF SEQUENCE NUMBERS WILL NOT BE REPEAT.
        
CREATE SEQUENCE SQ1 START WITH 1001 MINVALUE 1001 INCREMENT BY 4 MAXVALUE 1090;             

CREATE TABLE SQDEMO (SNO INT, NAME VARCHAR2(20));

INSERT INTO SQDEMO VALUES(SQ1.NEXTVAL,'GANESH');
INSERT INTO SQDEMO VALUES(SQ1.NEXTVAL,'KIRAN');
INSERT INTO SQDEMO VALUES(SQ1.NEXTVAL,'RAM');

SELECT * FROM SQDEMO;


